a=input('Enter the first number: ')
a=float(a)
b=input('Enter the second number: ')
b=float(b)
p=(a+b)
q=(a-b)
r=(a * b)
s=(a/b)
print('Addition: ',p)
print('Subtraction: ',q)
print('Multiplication: ',r)
print('Division: ',s)
